- src/lsp/cobol_common/srcloc.ml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_preproc/src_overlay.ml
Before this change we had a warning about a function not being available in OCaml 5.
> Remove fold on ephemerons

- .drom
- dune-project
- opam/cobol_common.opam
- src/lsp/cobol_common/basics.ml
- src/lsp/cobol_common/dune
- src/lsp/cobol_common/package.toml
- src/lsp/cobol_config/cobol_config.ml
- src/lsp/cobol_config/default.ml
- src/lsp/cobol_config/from_file.ml
- src/lsp/cobol_config/from_file.mli
- src/lsp/cobol_config/reserved_words.ml
- src/lsp/cobol_config/types.ml
- src/lsp/cobol_config/words.ml
- src/lsp/cobol_data/env.ml
- src/lsp/cobol_indent/indent_check.ml
- src/lsp/cobol_lsp/lsp_completion.ml
- src/lsp/cobol_parser/text_lexer.ml
- src/lsp/cobol_typeck/cobol_typeck.ml
- src/lsp/cobol_typeck/cobol_typeck.mli
- test/config_parsing/test_gnucobol_config.ml
This removes a lot of stuff from `Cobol_common.Basics`, that are not actually needed since we now also rely on `EzCompat` (from `ocplib-stuff`).
> Strip down `Cobol_common.Basics`, often replaceable by `EzCompat`

- .drom
- src/vscode/vscode-json/dune
- src/vscode/vscode-json/ezjsonm.ml
- src/vscode/vscode-json/ezjsonm.mli
- src/vscode/vscode-json/grammar.ml
- src/vscode/vscode-json/language.ml
- src/vscode/vscode-json/main.ml
- src/vscode/vscode-json/main.mli
- src/vscode/vscode-json/manifest.ml
- src/vscode/vscode-json/package.toml
- src/vscode/vscode-json/snippets.ml
- src/vscode/vscode-json/tasks.ml
- src/vscode/vscode-package-json/main.ml
- src/vscode/vscode-package-json/project.ml
* Support for comments in JSON files, using a patched version of Ezjsonm
* New options to parse various JSON files (grammars, languages, snippets, etc.)
* Print the content of JSON files in OCaml format to be able to easily integrate them in our modes
> Improve vscode-package-json

- src/lsp/cobol_parser/grammar_utils.ml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_preproc/preproc_engine.ml
- src/lsp/cobol_preproc/src_overlay.ml
- src/lsp/cobol_preproc/src_overlay.mli
This fixes a potential undefined behavior (infinite loop) in cache lookup, that may occur when rewinding tokens that are involved in composed source locations.
> Clear source overlay cache upon parser rewind

- src/lsp/cobol_indent/cobol_indent.ml
- src/lsp/cobol_indent/indenter.ml
- src/lsp/cobol_indent/indenter.mli
- src/lsp/cobol_lsp/lsp_request.ml
When indenting a file from the LSP, use the text from the current buffer, not the last version saved to disk (otherwise changes could disappear).
> Indent text from buffer, not disk

- package.json
- src/lsp/superbol_free_lib/project.ml
This PR sets the default value `superbol.path` to the executable name. This works when the `PATH` environment variable already points to the executable. This probably is not cross-compatible though.
> Default superbol.path option

- src/lsp/cobol_indent/cobol_indent.ml
- src/lsp/cobol_indent/indent_type.ml
- src/lsp/cobol_indent/indenter.ml
- src/lsp/cobol_indent/indenter.mli
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/superbol_free_lib/command_indent_file.ml
- src/lsp/superbol_free_lib/command_indent_range.ml
- test/lsp/lsp_formatting.ml
The indenter also now uses inferred formats properly.
Fixes #52
Note: Currently includes #73; do not merge before #73.
>  Only enable indenter on free format 

- src/lsp/cobol_indent/indent_check.ml
- src/lsp/cobol_indent/indent_type.ml
- src/lsp/cobol_indent/indent_util.ml
- src/lsp/cobol_indent/indent_util.mli
- src/lsp/cobol_indent/indenter.ml
We now use the current source format to indent each line.
Related cleanup: the indenter now uses an array rather than a list to represent the content of the file for performance.
Note: currently includes #93.
> Support change of reference format while indenting

- package.json
- src/lsp/superbol_free_lib/project.ml
- src/vscode/superbol-vscode-platform/superbol_commands.ml
- src/vscode/superbol-vscode-platform/superbol_commands.mli
- src/vscode/superbol-vscode-platform/superbol_instance.ml
- src/vscode/superbol-vscode-platform/superbol_instance.mli
- src/vscode/superbol-vscode-platform/superbol_languageclient.ml
- src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
Add a command to restart the language server. This will pick up changes to the `superbol.path` configuration option.
Fixes #88
Note that this allows a manual solution to #81 (making it possible to start the restart language server after changing `superbol.path` without having to reload the whole extension).
> Add "Superbol: Restart Language Server" command.

- package.json
- src/lsp/superbol_free_lib/project.ml
- src/vscode/vscode-json/manifest.ml
This PR fixes the `superbol.path` form that was not displayed because of a type error.
> Fix form for customizing `superbol.path`

- .gitattributes
Github shows changes to many files that are actually generated by `drom`. The new `.gitattributes` instructs it to hide the diffs by default.
Note: some of the generated files might still be relevant for review, and some others might be missing. So suggestions are welcome.
> Instruct github about some more auto-generated files

- src/lsp/cobol_lsp/lsp_document.ml
- src/lsp/cobol_lsp/lsp_server.ml
- src/lsp/cobol_preproc/preproc_engine.ml
- test/cobol_parsing/dune
- test/cobol_parsing/parser_testing.ml
- test/cobol_parsing/test_appending.ml
- test/cobol_parsing/test_stuttering.ml
The commit that matters most is 227b3689:
>    This fixes a bug introduced in 86e6cca6 by an uncareful optimization
>    of the computation.  Essentially, the meaning of `Failure` and
>    `Invalid_argument` exception in `List.nth` needed to be reversed.  The
>    included changes fix and improve the affected portion of code, and add
>    some new (high-level) tests to better exercise the rewinding code.
> Bugfix: lookup of pre-processor reset position upon rewind

- src/lsp/cobol_indent/cobol_indent.ml
- src/lsp/cobol_indent/indent_config.ml
- src/lsp/cobol_indent/indent_type.ml
- src/lsp/cobol_indent/indent_util.ml
- src/lsp/cobol_indent/indent_util.mli
- src/lsp/cobol_indent/indenter.ml
- src/lsp/cobol_indent/indenter.mli
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/superbol_free_lib/command_indent_file.ml
- src/lsp/superbol_free_lib/command_indent_range.ml
- test/lsp/lsp_formatting.ml
Internally, the indenter computes a diff (in terms of offsets) for each line that needs to change. Then, all the diffs are applied to the document, and a single edit that rewrites the full document is sent to the editor.
This PR changes the behavior to send small text edits that either add or remove whitespace instead.
> Use minimal diffs for the indenter

- src/lsp/cobol_indent/cobol_indent.ml
- src/lsp/cobol_indent/indent_check.ml
- src/lsp/cobol_indent/indent_config.ml
- src/lsp/cobol_indent/indent_config.mli
- src/lsp/cobol_indent/indent_type.ml
- src/lsp/cobol_indent/indent_util.ml
- src/lsp/cobol_indent/indent_util.mli
- src/lsp/cobol_indent/indenter.ml
- src/lsp/cobol_indent/indenter.mli
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/superbol_free_lib/command_indent_file.ml
- src/lsp/superbol_free_lib/command_indent_range.ml
- src/lsp/superbol_free_lib/command_project.ml
- src/lsp/superbol_free_lib/project_config.ml
- src/lsp/superbol_project/project_config.ml
- src/lsp/superbol_project/project_config.mli
The indent configuration is now exposed by the `Cobol_indent` module and loaded from the `superbol.toml` file. For the sake of simplicity, this does not change the internal representation of the indent configuration, even though it requires us to expose the configuration as a hash table in `Indent_type.ml`. Be responsible.
Fixes #46
> Use per-project file for indent configuration

- src/lsp/cobol_preproc/src_lexer.mll
- src/lsp/cobol_preproc/src_lexing.ml
- src/lsp/cobol_preproc/src_lexing.mli
The "bug" is *only* about semantic tokens: none were emitted for source code that followed separators encountered *after* the right margin. As a result of that they were just not subject to syntax highlighting.
> Bugfix: missing semantic tokens for words on the right of separators in the right margin

- src/lsp/cobol_indent/indent_config.ml
- test/lsp/lsp_formatting.ml
Fixes the following:
> (BTW l'indenteur actuel ajoute une offset de 1 avant les titres et
sections et paragraphes, qu'il faudrait laisser alignés sur la marge de gauche comme dans la plupart des fichiers COBOL qu'on voit).
> Do not indent inside procedure division.

- Makefile.header
- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/node-js-stubs/node.ml
- src/vscode/node-js-stubs/node.mli
- src/vscode/node-js-stubs/node_stub.js
- src/vscode/superbol-vscode-platform/superbol_instance.ml
- src/vscode/superbol-vscode-platform/superbol_instance.mli
- src/vscode/superbol-vscode-platform/superbol_languageclient.ml
- src/vscode/superbol-vscode-platform/superbol_languageclient.mli
- src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
This patch makes the VS Code extension look for a bundled executable in the following order (and with a `.exe` suffix on Windows):
- `_dist/superbol-free-${platform}-${arch}`
- `_dist/superbol-free-${platform}`
- `_dist/superbol-free`
So for instance on x64 Linux we will look for:
- `_dist/superbol-free-linux-x64`
- `_dist/superbol-free-linux`
- `_dist/superbol-free`
On recent Macs we will look for:
- `_dist/superbol-free-darwin-arm64`
- `_dist/superbol-free-darwin`
- `_dist/superbol-free`
And on Windows we will look for
- `_dist/superbol-free-win32-x64.exe`
- `_dist/superbol-free-win32.exe`
- `_dist/superbol-free.exe`
This will also allow tackling #76 once we actually put the executables in the extension. It also allows some flexibility between making "slim" per-platform extensions or …
> Look for bundled superbol-free executable

- sphinx/commands.rst
- src/lsp/cobol_lsp/lsp_project.mli
- src/lsp/cobol_lsp/lsp_project_cache.ml
- src/lsp/cobol_lsp/lsp_project_cache.mli
- src/lsp/cobol_lsp/lsp_server_loop.ml
- src/lsp/superbol_free_lib/arg_utils.ml
- src/lsp/superbol_free_lib/arg_utils.mli
- src/lsp/superbol_free_lib/command_lsp.ml
- src/lsp/superbol_free_lib/project.ml
- src/lsp/superbol_project/project.ml
- src/lsp/superbol_project/project.mli
- test/lsp/lsp_testing.ml
When provided, `--storage-directory=DIR` forces cache files to reside inside the given directory; this prevents the creation of `_superbol` directories at the root of project trees.
Side changes include enhancements to the description of project layouts, and command-line flags to enable or disable caching.
Preliminary steps to address #107
> Add new argument to specify the directory for storing cache files

- .drom
- src/lsp/superbol_free_lib/dune
- src/lsp/superbol_free_lib/package.toml
This shall help avoid (indirectly) depending on `lwt` (and therefore, `threads`).
> Depend on `ez_api.encoding` instead of the whole of `ez_api`

- .drom
- .vscodeignore
- Makefile
- Makefile.drom-tpl
- Makefile.header
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/superbol-vscode-platform/superbol_instance.ml
Included changes add a new `all-vsix-packages` build target, that constructs VSIX files for `linux-x64` and `win32-x64` targets. Generated files are named `superbol-vscode-platform-<version>-<target>.vsix`.
> Provide platform-dependent VSIX files

- test/cobol_parsing/test_picture_parsing.ml
A PIC string like `999$` appears to be accepted according to COBOL 2014.
> Add missing test for fixed insertion of currency symbol

- src/lsp/cobol_lsp/lsp_error.ml
- src/lsp/cobol_lsp/lsp_error.mli
- src/lsp/cobol_lsp/lsp_io.ml
- src/lsp/cobol_lsp/lsp_io.mli
- src/lsp/cobol_lsp/lsp_notif.ml
- src/lsp/cobol_lsp/lsp_project_cache.ml
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_request.mli
- src/lsp/cobol_lsp/lsp_server.ml
- src/lsp/cobol_lsp/lsp_server.mli
- src/lsp/cobol_lsp/lsp_server_loop.ml
This shall make the LSP actually save its caches when used in VS Code on windoze (on Linux, VS Code's shutdown is cleaner so caches already worked fine).
> Properly shut the LSP server down upon end of input stream

- src/lsp/cobol_lsp/lsp_debug.ml
- src/lsp/cobol_lsp/lsp_io.ml
- src/lsp/cobol_lsp/lsp_request.ml
Add a Lsp_debug module that logs the exchanges between the editor and the LSP server in a file specified by the env SUPERBOL_LSP_DEBUG
(I split the PR into multiple ones to easy merging)
> Some improvements while debugging the LSP

- README.md
- sphinx/building-superbol.rst
In order to build SuperBOL, we need to initialise and update submodules first.
> Add build instructions for SuperBOL

- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_preproc/src_overlay.ml
- src/lsp/cobol_preproc/src_overlay.mli
- src/lsp/cobol_preproc/text_supplier.ml
This avoids a potential infinite loop in cache lookup by the source overlay manager. Before this change, new tokens and location limits were produced before the cache was cleared, which could led to an infinite loop during lookup in the cache.
> Bugfix: upon rewind, clear source overlay locations cache earlier

- src/lsp/cobol_parser/grammar.mly
Such locations now span over section headers; before, they started at the first item.
> Fix source locations of data division's sections

- src/lsp/cobol_common/copybook.ml
- src/lsp/cobol_common/copybook.mli
- src/lsp/cobol_preproc/preproc_directives.ml
- src/lsp/cobol_preproc/preproc_engine.ml
- src/lsp/cobol_preproc/preproc_engine.mli
- src/lsp/cobol_preproc/preproc_grammar.mly
- src/lsp/cobol_preproc/src_input.ml
- src/lsp/cobol_preproc/src_reader.ml
- src/lsp/cobol_preproc/src_reader.mli
- test/output-tests/syn_copy.expected
- test/output-tests/used_binaries.expected
Before these changes, a `COPY something OF "."` interpreted "." w.r.t the current working directory.  Now, the "." is interpreted w.r.t the directory name of the file where the `COPY` statement is found.
This allows the LSP to properly handle one of the NIST-COBOL85 tests, whatever the project directory (from which every relative path is interpreted).
> Fix lookup when `COPY <text-name> IN/OF <relative path>` is used

- src/lsp/cobol_lsp/lsp_diagnostics.ml
- src/lsp/cobol_lsp/lsp_diagnostics.mli
- src/lsp/cobol_lsp/lsp_position.ml
- src/lsp/cobol_lsp/lsp_position.mli
- src/lsp/cobol_lsp/lsp_project.ml
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_request.mli
- src/lsp/cobol_lsp/lsp_server.ml
Before this change, copied definitions and references were localized on the corresponding `COPY` within the main source program.
> Make goto-def and find-refs return locations within copybooks

- Makefile.header
- README.md
- sphinx/building-superbol.rst
The `-g` option in `npm install -g yarn` is necessary in order to be able to use the `yarn install` command.
> Substitute `npx yarn` for plain `yarn`

- src/lsp/cobol_lsp/lsp_request.ml
Hover requests are parameterized with a position in a source file, that essentially describes where the cursor is. To determine what to answer, the LSP searches for a range in the source file that both: (i) contains the given position, and (ii) corresponds to a pre-processing operation. To do so, the LSP scans some sort of log/journal created by the pre-processor, and projects the source location that is associated with `COPY` or replacement entries onto the given file name to obtain a range in the source file. The position is then checked against this range.
The previous implementation relied on the assumption that it is always possible to project a source location against the source filename of the *main* program (which is the one on which we are hovering here). However, while this …
> Harden the LSP against copied source locations in pre-processor logs

- src/lsp/superbol_free_lib/command_check_syntax.ml
- src/lsp/superbol_free_lib/main.ml
See issue https://github.com/OCamlPro/superbol-studio-oss/issues/142
This PR adds a "check syntax" command to check the presence of syntax errors in a COBOL file. It can be used as follows:
```
./superbol-free[...] check syntax <path to COBOL file>
```
> Add check syntax command

- .vscodeignore
- package.json
- schemas/superbol-schema.json
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/vscode-json/manifest.ml
Gathers some changes from #154, for easier review:
- Customization of activation events for the extension;
- A JSON schema that can be used by TOML-dedicated LSPs to validate and edit the `superbol.toml` configuration file.
Regarding the latter point, this PR adds a dependency to the `tamasfe.even-better-toml` VS Code extension. The idea may be, if and when we find out how that can be done, to have this as a "suggestion" only, not as a mandatory dependency.
> Manifest improvements

- src/lsp/cobol_config/cobol_config.ml
This should allow the extension to work properly on typical Linux setups.
> Consider Linux-specific standard GnuCOBOL configuration paths

- src/lsp/cobol_lsp/lsp_project.ml
- src/lsp/cobol_lsp/lsp_project.mli
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_server.ml
- src/lsp/cobol_lsp/lsp_server.mli
- src/lsp/superbol_project/project.mli
- src/lsp/superbol_project/project_config.ml
- src/lsp/superbol_project/project_config.mli
- src/vscode/superbol-vscode-platform/superbol_commands.ml
- src/vscode/superbol-vscode-platform/superbol_instance.ml
Gathers two (hopefully) self-explaining commits:
- Avoid full reparses when transitioning between equivalent configurations;
- Remove requirement to have a file open to create `superbol.toml` files.
Includes a tiny bit of refactoring as well.
> Smoother config management

- src/vscode/superbol-vscode-platform/superbol_tasks.ml
By default in build tasks, let GnuCOBOL use its default policy for dealing with case in lookup of copybooks.
> Remove `-ffold-copy=LOWER` from default extra options in build tasks

- src/lsp/cobol_config/cobol_config.ml
Installation of GnuCOBOL on various Linux distributions appear to place config files in `/etc/gnucobol`.
> Add "/etc/gnucobol" in default search path for GnuCOBOL config files

- README.md
- src/lsp/cobol_lsp/lsp_server.ml
- src/lsp/cobol_lsp/lsp_server.mli
- src/lsp/cobol_lsp/lsp_server_loop.ml
- src/lsp/cobol_lsp/lsp_server_loop.mli
- src/lsp/superbol_free_lib/arg_utils.ml
- src/lsp/superbol_free_lib/arg_utils.mli
- src/lsp/superbol_free_lib/command_lsp.ml
- test/lsp/lsp_testing.ml
This temporary measure aligns the behavior of the LSP server with the current documentation in the `README.md`: we suppress diagnostics for dialects other than COBOL85 to avoid overwhelming users with wrong diagnostics; we keep them for COBOL85 as the current parser has been tested quite extensively on this dialect.
> Filter out LSP diagnostics for dialects other than COBOL85

- .drom
- Makefile
- Makefile.drom-tpl
- Makefile.header
- scripts/static-build.sh.drom-tpl
This is achieved using docker, and on demand by setting `BUILD_STATIC_EXECS=true`
> Provide means to statically link the LSP server for Linux

- README.md
- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
- studio/CHANGELOG.md
- studio/LICENSE.md
- studio/README.md
- studio/icon.png
- studio/package.json
- Update the main extension's description, and remove its dependency to `tamasfe.even-better-toml`;
- Add an extension pack into the `studio` sub-directory. Calling `vsce package --out superbol-studio-pack-0.1.0.vsix` into `studio` will build a pack that can directly be published on the marketplace.
> SuperBOL Studio Pack

- .drom
- .gitignore
- .vscodeignore
- Makefile.header
- drom.toml
- src/lsp/cobol_config/cobol_config.ml
- src/vscode/superbol-vscode-platform/superbol_instance.ml
- src/vscode/superbol-vscode-platform/superbol_instance.mli
- src/vscode/superbol-vscode-platform/superbol_languageclient.ml
- src/vscode/superbol-vscode-platform/superbol_languageclient.mli
- src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
With these changes, having an installed version of GnuCOBOL is no longer required for the LSP part of the extension to work.
> Ship GnuCOBOL config files in the VSIX, and use them as fallback

- src/lsp/cobol_lsp/lsp_request.ml
These changes make the LSP server transparently ignore errors that may arise from requests about documents that are recognized as copybooks.
Previously, error notifications were shown in these cases.
> Harden the LSP server against requests about copybook documents

- src/lsp/cobol_preproc/text.ml
- src/lsp/cobol_preproc/text.mli
- src/lsp/cobol_preproc/text_processor.ml
Before this change, `REPLACE ==x==` did not replace occurrences of `X`.
> Match pseudo-text for exact replacement case insensitively

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/compilation_group.ml
- src/lsp/cobol_ptree/compilation_group_visitor.ml
- test/output-tests/syn_definition.expected
The grammar could recognise the `INITIAL`, `RECURSIVE` and `COMMON` keywords after `PROGRAM-ID. id IS?` but not:
- `INITIAL COMMON` and `RECURSIVE COMMON`;
- `COMMON INITIAL` and `COMMON RECURSIVE`
I followed the [grammar of GnuCOBOL](https://github.com/OCamlPro/gnucobol/blob/89c45a3bc80c2ca6302382bd40fdc585436d65f9/cobc/parser.y#L3992).
> Handle `COMMON` keyword in `PROGRAM-ID`

- src/lsp/cobol_parser/grammar.mly
In the `INSPECT ... TALLYING` statement, it is possible to write `FOR ALL CHARACTERS` FOR `FOR CHARACTERS`.
Such syntax occurs in [ACAS](https://sourceforge.net/projects/acas/) (`makesqltable-original.cbl` ligne 178, 196, 210, 243) and is accepted by the GnuCOBOL compiler.
> Fix INSPECT TALLYING FOR ALL CHARACTERS

- src/lsp/cobol_preproc/src_lexer.mll
- src/lsp/cobol_preproc/src_lexing.ml
Simplifies handling of floating comments in preprocessor lexer
> Fix lexing of `*>` and `>>` that may appear in text words

- src/lsp/cobol_parser/grammar.mly
- test/output-tests/syn_file.expected
I followed [GnuCOBOL's](https://github.com/OCamlPro/gnucobol/blob/89c45a3bc80c2ca6302382bd40fdc585436d65f9/cobc/parser.y#L5635) syntax where not only `KEY` but also `RECORD` is optional.
Such syntax is used in [BankDemo](https://github.com/MicroFocus/BankDemo/blob/c1d49ed2fc9285d6da3b25f01e8265aa86747847/sources/cobol/core/ZBNKLOAD.cbl#L77).
> Fix ALTERNATE clause of SELECT statement

- src/lsp/superbol_free_lib/common_args.ml
That was mistakenly moved to a place that made the CLI tool ignore any `--verbose` argument.
Obviously that means we're not testing this…
> Fix handling of verbosity flag

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/branching_statements.ml
- src/lsp/cobol_ptree/simple_statements.ml
- src/lsp/cobol_ptree/statements_visitor.ml
- test/output-tests/run_extensions.expected
- test/output-tests/run_fundamental.expected
- test/output-tests/run_misc.expected
The ENTRY statement was not recognised by the grammar in lines such as:
```cobol
entry    "delfolioMT" using   File-Access ACAS-DAL-Common-data DUMMY-REC.
```
coming from [ACAS](https://sourceforge.net/projects/acas/) in `dummy-rdbmsMT.cbl:127`.
Something I am not very sure of is that I ignored string literals in the visitors.
References:
- [GnuCOBOL parser.y](https://github.com/OCamlPro/gnucobol/blob/gcos4gnucobol-3.x/cobc/parser.y)
- [Microfocus documentation](https://www.microfocus.com/documentation/visual-cobol/vc50all/VS2019/HRLHLHPDF902.html)
> Handle ENTRY statement

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/data_descr.ml
- src/lsp/cobol_ptree/data_descr_visitor.ml
- src/lsp/cobol_ptree/data_sections.ml
- src/lsp/cobol_ptree/data_sections_visitor.ml
The `RECORDING MODE` clause used a single-constructor type
```ocaml
type recording_mode_clause =
| RecordingMode of recording_mode
```
which was not necessary. A visitor and pretty printer was defined for it but I pushed those one level upper (in data sections).
> Simplify handling of RECORDING MODE clause

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/branching_statements.ml
- src/lsp/cobol_ptree/statements_visitor.ml
- test/output-tests/run_misc.expected
The `GO TO ENTRY` and `GO TO ENTRY ... DEPENDING` statements were not recognised.
DRAFT: currently stuck on some "production never reduced" errors. There are obvious conflicts but I did not looked enough into it: `GO TO ENTRY ...` can be parsed as
```
GO TO
ENTRY ...
```
or
```
GO TO ENTRY ...
```
> Add GO TO ENTRY statement

- src/lsp/cobol_parser/grammar.mly
- test/output-tests/reparse.expected
The keyword `IS` can be optional in `RECORDING MODE`.
This syntax occurs in `ACAS/common/acas-get-params.cbl:105`. For instance:
```cobol
FD  ACAS-Params
recording mode variable.
```
> Fix optional IS in RECORDING MODE

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/simple_statements.ml
- src/lsp/cobol_ptree/statements_visitor.ml
The point was to make the code coherent with [pull request #256](https://github.com/OCamlPro/superbol-studio-oss/pull/256).
> Use alphanum instead of alphanum_string in ENTRY statement

- src/vscode/superbol-vscode-platform/superbol_tasks.ml
> Properly resolve the default debugger launch configuration

- .drom
- dune-project
- opam/superbol_preprocs.opam
- src/lsp/cobol_lsp/lsp_document.ml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_parser/parser_options.ml
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_parser/text_tokenizer.mli
- src/lsp/superbol_free_lib/common_args.ml
- src/lsp/superbol_preprocs/dune
- src/lsp/superbol_preprocs/generic.ml
- src/lsp/superbol_preprocs/main.ml
- src/lsp/superbol_preprocs/package.toml
- test/cobol_parsing/parser_testing.ml
- test/output-tests/gnucobol.ml
- test/output-tests/reparse.ml
Also add the ability to pass some state upon each successive scan of blocks for the same language.
> Use per-language scanners for `EXEC`/`END-EXEC` blocks

- src/lsp/cobol_parser/context/gen_context.ml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_parser/recovery.ml
- test/cobol_parsing/cS_tokens.ml
Fixing that was an epic fight :sweat_smile:.
Before these changes, some contexts were not exited properly. For instance `01 x CONSTANT 12345.` entered context `constant`, but did not leave it. The reason was simple: this context is here left via a shift instead of a reduction, which was previously though as the only means for a grammar rule to be left. The latter assumption turned out to be wrong, and this PR addresses this issue.
Prior to this PR, the new test failed, with the `BYTE-LENGTH` words wrongly recognized as keywords.
> Bugfix: handle contexts that terminate upon shift instead of reduce

- src/lsp/cobol_data/data_visitor.ml
- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_ptree/compilation_group.ml
- src/lsp/cobol_ptree/compilation_group_visitor.ml
- src/lsp/cobol_ptree/data_descr.ml
- src/lsp/cobol_ptree/data_descr_visitor.ml
- src/lsp/cobol_typeck/old_env_builder.ml
- src/lsp/cobol_typeck/old_prog_builder.ml
- src/lsp/cobol_typeck/typeck_units.ml
- test/output-tests/run_fundamental.expected
- test/output-tests/syn_functions.expected
The period after `FUNCTION-ID` is also made optional.
(Partly) extracted from #262
> Alphanumeric names for more COBOL units

- src/lsp/cobol_parser/grammar.mly
This is to properly parse the NIST85 test-suite.
> Restore support for `STOP <literal>`

- .gitattributes
- CHANGELOG.md
- src/.gitattributes
- src/lsp/cobol_parser/grammar_tokens.mly
- src/lsp/cobol_parser/parser_diagnostics.ml
- src/lsp/cobol_parser/text_categorizer.mll
- src/lsp/cobol_parser/text_lexer.ml
- src/lsp/cobol_parser/text_lexer.mli
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_preproc/src_lexer.mll
- src/lsp/cobol_preproc/src_lexing.ml
- src/lsp/cobol_preproc/src_lexing.mli
- src/lsp/cobol_preproc/src_reader.ml
- src/lsp/cobol_preproc/src_tokenizer.ml
- src/lsp/cobol_preproc/text.ml
- src/lsp/cobol_preproc/text_printer.ml
- src/lsp/cobol_preproc/text_processor.ml
- src/lsp/cobol_preproc/text_types.ml
- test/cobol_parsing/decimal_point.ml
- test/cobol_parsing/dune
- test/cobol_parsing/exec_blocks.ml
- test/output-tests/preproc.expected
- test/output-tests/run_misc.expected
- test/output-tests/syn_misc.expected
These changes shall enable `EXEC`/`END-EXEC` blocks with languages in which commas and semicolons are relevant (like SQL).  This is achieved by adding a new `Separator` constructor for elements of manipulated text.
Further handling of weird GC extensions that allow `77,x;PIC,99,99.` (equivalent to `77 x PIC 99,99.`) required some rewriting of the scanning code.
> Better handling of `,` & `;` separators in manipulated text

- CHANGELOG.md
- src/lsp/cobol_data/data_memory.ml
- src/lsp/cobol_data/data_memory.mli
- src/lsp/cobol_typeck/typeck_data_diagnostics.ml
- src/lsp/cobol_typeck/typeck_data_items.ml
- test/cobol_typeck/ko_renames.ml
- test/cobol_typeck/ok_renames.ml
Symbolic sizes are in bits, sizes given to display data categories are in bytes.
Closes #294
> Bugfix: size of `RENAMES` range

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_completion.ml
- src/lsp/cobol_parser/expect/gen_expect.ml
- src/lsp/cobol_parser/grammar_expect.mli
- test/lsp/lsp_completion.ml
Replaced `reducible_productions_in` and `nullable_nonterminals_in` with `actions_in`
Created new type `action` to unify both `feed` and `reduce` action possibility
> Refactor `Expect` api for completion

- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_parser/recovery.ml
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_parser/text_tokenizer.mli
- test/cobol_parsing/dune
- test/cobol_parsing/parser_testing.ml
- test/cobol_parsing/test_intrinsics_registration.ml
- test/cobol_parsing/test_targeted_insertions.ml
Includes an automated test that relies on the current requirement for function procedure divisions to start with a paragraph or section title. This test may need to be adapted when this requirement is lifted (or it won't test the issue properly anymore).
> Probe and apply post-actions on parser recovery path

- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_request.mli
- src/lsp/superbol_preprocs/main.ml
- test/cobol_parsing/exec_blocks.ml
- test/cobol_parsing/parser_testing.ml
- test/cobol_parsing/tokens.ml
- test/cobol_typeck/typeck_testing.ml
- test/lsp/lsp_hover.ml
- test/output-tests/reparse.ml
- Disable hover on whole data item defintions for now: it's too invasive;
- Disable scanning of `EXEC SQL` blocks by the LSP server: it is still brittle and does not benefit from the result.
> Various UX adjustments

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_capabilities.ml
- src/lsp/cobol_lsp/lsp_document_symbol.ml
- src/lsp/cobol_lsp/lsp_document_symbol.mli
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_request.mli
- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/compilation_group.ml
- src/lsp/cobol_ptree/compilation_group_visitor.ml
- test/lsp/lsp_document_symbol.ml
Documentation: [documentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol).
Mainly used to show [outline](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) and [breadcrumbs](https://code.visualstudio.com/docs/getstarted/userinterface#_breadcrumbs) in VSC.
> Add support for the `textDocument/documentSymbol` LSP request

- CHANGELOG.md
- src/lsp/cobol_parser/grammar.mly
- test/lsp/lsp_document_symbol.ml
Added required . after `METHOD-ID. name`
> Fix `method_id_paragraph` syntax

- CHANGELOG.md
- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
- syntaxes/language-configuration.json
+ Fix for https://github.com/OCamlPro/superbol-studio-oss/issues/326
+ Brackets highlighting
+ Enter pattern for editions of fixed-format source code
> Add language configuration file to fix word wrapping and improve UX

- .drom
- dune-project
- opam/cobol_lsp.opam
- opam/osx/cobol_lsp-osx.opam
- opam/windows/cobol_lsp-windows.opam
- src/lsp/cobol_lsp/package.toml
Temporary to let other PR build
A PR to upgrade to 1.19 will be required later
> Set upperbound on lsp version

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_completion.ml
- test/lsp/lsp_completion.ml
Show  `Instrinsic`, `Paragraph` and `Section` as detail on completion entries
> Show more detailed type information on completion

- CHANGELOG.md
- package.json
- src/lsp/cobol_lsp/lsp_document.ml
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/superbol-vscode-platform/superbol_languageclient.ml
- src/vscode/superbol-vscode-platform/superbol_tasks.ml
- syntaxes/dumpfile.tmLanguage.json
- syntaxes/list-n-dump-configuration.json
- syntaxes/listfile.tmLanguage.json
> Add support for dump and listing files

- .drom
- src/lsp/cobol_lsp/lsp_completion.ml
- src/lsp/cobol_parser/cobol_parser.ml
- src/lsp/cobol_parser/dune
- src/lsp/cobol_parser/grammar_tokens_printer.ml
- src/lsp/cobol_parser/keywords/gen_keywords.ml
- src/lsp/cobol_parser/package.toml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_parser/text_keywords.mli
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_parser/text_tokenizer.mli
- test/cobol_parsing/parser_testing.ml
The old `pp_token` of Text_tokenizer didn't have a prime even though it was a pretty printer for `token with_loc`
> Unify `pp_token` of Text_tokenizer with other pp

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_capabilities.ml
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_request.mli
- src/lsp/cobol_typeck/typeck_procedure.ml
- src/vscode/superbol-vscode-platform/superbol_commands.ml
- test/lsp/lsp_codelens.ml
Show references count via codelens in data division
Closes #340
> Add support for Codelens requests

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_lookup.ml
- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/branching_statements.ml
- src/lsp/cobol_ptree/statements_visitor.ml
Remove possibility to have more than one procedure when no `DEPENDING` clause is set
> Improve `GO` statement grammar

- README.md
and back-reference for "show copybooks on hover"
this originates on me wondering why it did not work "as suggested by the README".
Question: Wouldn't it be reasonable for the LSP to have a list of the file names and if there's only a single one to match the copybook for hover/show definition`?
This would lead to most environments working "out of the box".
> more explanations on settings

- CHANGELOG.md
- src/lsp/cobol_common/srcloc.ml
- src/lsp/cobol_common/srcloc.mli
- src/lsp/cobol_lsp/lsp_completion.ml
- src/lsp/cobol_lsp/lsp_document.ml
- src/lsp/cobol_parser/parser_engine.ml
- src/lsp/cobol_parser/parser_engine.mli
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_preproc/src_overlay.ml
- test/cobol_parsing/tokens.ml
- test/lsp/lsp_completion.ml
- test/lsp/lsp_inspect.ml
Removes a potential infinite loop with comment entries that are not terminated (reaching end of input); also avoids source location errors during parser exploration by LSP completion code.
> Fix source location management during completion

- .drom
- CHANGELOG.md
- Makefile
- Makefile.drom-tpl
This fixes binaries included in VSIXs for Darwin platforms.
> Always honor `BUILD_STATIC_EXECS`

- Makefile.header
People say that extension is better than most officially released ones; let's trust people.
> Stop flagging built VSIXs as pre-releases

- .drom
- .github/workflows/workflow.yml
- .github/workflows/workflow.yml.drom-tpl
- drom.toml
Fixes #113 (mostly — `superbol-free` is still left out).
> Update github workflow to build VSIX artifacts

- SUPPORT.md
Closes #400 (after further discussions on the contents of this file).
> Add `SUPPORT.md`

- .drom
- src/lsp/superbol-free/linking_flags.sh
- src/lsp/superbol-free/linking_flags.sh.drom-tpl
Included changes turn errors about invalid requests of static linking flags (calls to `linking_flags.sh`) into warnings.  At the moment these requests are also performed for js_of_ocaml compilation modes, which prevents one from globally setting `LINKING_MODE=static`.
> Avoid compilation failure when querying static linking flags outside Alpine

- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
which should highlight the complete line and reference not only column 1 in the problem pane
warning: this is untested, it just worked when I tested it locally with my own problemMatcher definitions (and got that hint from a vscode dev); obviously "some day" we should emit columns from cobc as well - but if we do it the gcc way "location" should handle those fine (we likely will need to adjust the regex, when the time comes)
... maybe I try the CI build of this PR some day to test the result, but there's possibly someone else faster :-)
> switch problemMatcher patterns from line to locations
