OCamlPro/superbol-studio-oss

- src/lsp/superbol_free_lib/command_texi2rst.ml
This command is an awful hack, but for now, it does the job...
> Improve texi2rst subcommand for GnuCOBOL manual

- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_parser/text_tokenizer.ml
- src/lsp/cobol_preproc/preproc_keywords.ml
- src/lsp/cobol_preproc/preproc_tokens.mly
- src/lsp/cobol_preproc/src_lexer.mll
- src/lsp/cobol_preproc/src_lexing.ml
- src/lsp/cobol_preproc/src_lexing.mli
- test/cobol_parsing/compiler_directives.ml
- test/cobol_parsing/dune
- test/cobol_parsing/parser_testing.ml
- test/output-tests/configuration.expected
- test/output-tests/listings.expected
- test/output-tests/run_extensions.expected
- test/output-tests/run_file.expected
- test/output-tests/run_misc.expected
- test/output-tests/run_ml.expected
- test/output-tests/run_refmod.expected
- test/output-tests/run_reportwriter.expected
- test/output-tests/run_subscripts.expected
- test/output-tests/syn_misc.expected
Also removes reporting of dialect-specific support from the parsing phase.
> Fix and improve support for some compiler directives

- src/lsp/superbol_free_lib/command_switch.ml
* `switch build` can be reused on the same branch. The current switch and links are correctly updated.
* Add MANPATH and LOCPATH to `~/.config/gnucobol/env` and `switch env`
> Fixes in switch subcommand

- .drom
- dune-project
- opam/cobol_preproc.opam
- src/lsp/cobol_indent/indenter.ml
- src/lsp/cobol_preproc/dune
- src/lsp/cobol_preproc/package.toml
- src/lsp/cobol_preproc/preproc_diagnostics.ml
- src/lsp/cobol_preproc/preproc_engine.ml
- src/lsp/cobol_preproc/preproc_engine.mli
- src/lsp/cobol_preproc/src_format.ml
- src/lsp/cobol_preproc/src_format.mli
- src/lsp/cobol_preproc/src_input.ml
- src/lsp/cobol_preproc/src_lexing.ml
- src/lsp/cobol_preproc/src_lexing.mli
- src/lsp/cobol_preproc/src_reader.ml
- src/lsp/cobol_preproc/src_reader.mli
- src/lsp/superbol_free_lib/command_pp.ml
- test/cobol_preprocessing/auto_sourceformat.ml
- test/cobol_preprocessing/auto_sourceformat_rewind.ml
- test/cobol_preprocessing/compiler_directives.ml
- test/cobol_preprocessing/dune
- test/cobol_preprocessing/preproc_testing.ml
- test/lsp/lsp_basics.ml
- test/lsp/lsp_definition.ml
- test/lsp/lsp_formatting.ml
- test/lsp/lsp_hover.ml
- test/lsp/lsp_references.ml
- test/output-tests/reparse.ml
- test/output-tests/syn_misc.expected
> Implement autodetection of source format as in GnuCOBOL

- src/lsp/superbol_free_lib/command_texi2rst.ml
We will have to wait for PR https://github.com/OCamlPro/gnucobol-docs/pull/4 to be merged upstream.
> [WIP] Update texi2rst to take into account removal of numbers in gnucobol-docs

- src/lsp/cobol_lsp/cobol_lsp.ml
- src/lsp/cobol_lsp/lsp_debug.ml
- src/lsp/cobol_preproc/src_overlay.ml
- src/lsp/cobol_preproc/src_overlay.mli
- src/lsp/superbol_free_lib/command_lsp.ml
- src/lsp/superbol_free_lib/command_util.ml
- src/lsp/superbol_free_lib/main.ml
This PR contains two commits:
* one to add debug stuff to help solving bugs by outputing in logs and reducing the size of these logs by detecting cycles
* one to fix the bug in src_overlay, that happens because the code is looking for an exact match, that actually does not exist
> fix infinite loop in src_overlay

- src/lsp/cobol_config/cobol_config.ml
… as is typically the case on Windose.
> Better handle config lookup on Windose

- src/vendor/ez_toml/v1.ml
> Fix missing terminating newline for TOML files

- src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
> Try restarting the LSP server upon change of `superbol.lsp-path` setting

- package.json
- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/vscode-json/manifest.ml
- syntaxes/COBOL.tmLanguage.json
- test/lsp/lsp_hover.ml
> Use syntax file for colorization of text that miss semantic tokens

- src/lsp/superbol_free_lib/command_project.ml
- src/vendor/ez_toml/COMMIT.md
- src/vendor/ez_toml/internal_printer.ml
Also small fix in `superbol-free project init`
> Fix missing comments in superbol.toml (fix in ez_toml)

- src/lsp/cobol_parser/context/gen_context.ml
- src/lsp/cobol_parser/grammar.mly
- src/lsp/cobol_ptree/branching_statements.ml
- src/lsp/cobol_ptree/common.ml
- src/lsp/cobol_ptree/statements_visitor.ml
- src/lsp/cobol_ptree/terms.ml
- src/lsp/cobol_ptree/terms_visitor.ml
> Merge constructors for GO TO statement

- test/syntax-todo/syntax-done.at
- test/syntax-todo/syntax-todo.at
Please don't forget to update those ;)
> Update syntax tests

- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
Follows OCamlPro/superbol-vscode-debug/pull/6.
> Update the debug extension

- CHANGELOG.md
- package.json
- src/lsp/superbol_free_lib/vscode_extension.ml
- src/vscode/superbol-vscode-platform/superbol_tasks.ml
> Support building modules instead of executable programs

- .drom
- dune-project
- opam/cobol_parser.opam
- opam/osx/cobol_parser-osx.opam
- opam/windows/cobol_parser-windows.opam
- src/lsp/cobol_parser/package.toml
- src/lsp/cobol_parser/post/gen_post_actions.ml
- src/vendor/ez_toml/dune
This has been tested with menhir versions `20230415` and `20231231` and works fine
> Bump menhir version + update merlin submodule

- src/lsp/cobol_indent/config.ml
- src/lsp/cobol_indent/main.ml
- src/lsp/cobol_indent/scanner.ml
- src/lsp/cobol_indent/scanner.mli
- src/lsp/cobol_indent/types.ml
- src/lsp/superbol_free_lib/common_args.ml
Some improvements to return more information in case this scanner is used instead of the COBOL parser to retrieve faster information (but less exact)
> cobol_indent : scanner improvements, to be used for cartography

- CHANGELOG.md
- src/lsp/cobol_data/data_picture.ml
- src/lsp/cobol_data/data_picture.mli
- src/lsp/cobol_data/data_printer.ml
- src/lsp/cobol_lsp/lsp_data_info_printer.ml
- test/lsp/lsp_hover.ml
First step for: https://github.com/OCamlPro/superbol-studio-oss/issues/296
Example of result:
```cobol
PIC X USAGE DISPLAY
```
```cobol
PIC -BZZZ,ZZ9.99 USAGE DISPLAY
```
> Add raw picture string to hover info

- src/lsp/cobol_lsp/lsp_project_cache.ml
- src/lsp/cobol_lsp/lsp_server.ml
> Silence cache-related errors

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_data_info_printer.ml
- src/lsp/cobol_lsp/lsp_request.ml
- test/lsp/lsp_hover.ml
> Show documentation comment on variable hover

- src/lsp/cobol_lsp/lsp_request.ml
- src/lsp/cobol_lsp/lsp_response.ml
- src/lsp/cobol_lsp/lsp_server.ml
- src/lsp/cobol_lsp/lsp_server.mli
- test/lsp/lsp_testing.ml
> Restrict use of relative glob patterns

- .drom
- dune-project
- src/vendor/vscode-ocaml-platform/src-bindings/interop/package.toml
- src/vendor/vscode-ocaml-platform/src-bindings/node/package.toml
- src/vendor/vscode-ocaml-platform/src-bindings/vscode/package.toml
- src/vendor/vscode-ocaml-platform/src-bindings/vscode_languageclient/package.toml
- src/vscode/vscode-debugadapter/package.toml
- src/vscode/vscode-debugprotocol/package.toml
Workaroud [this weird error in `dune`](https://github.com/ocaml/dune/issues/5567).
> Workaround issue with dune and empty packages

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_project_cache.ml
- src/lsp/cobol_lsp/lsp_request.ml
> Include version and platform info on LSP server startup

- CHANGELOG.md
- src/lsp/cobol_lsp/lsp_semtoks.ml
> Use a tail-recursive merge when combining lists of semantic tokens
